### ISSUE TITLE
com_baidu_cafe_remote项目下有错误

### ISSUE THREAD

**Issue by rainy1216** [baidu/Cafe#24]
此项目下SystemLib类下
import android.app.ActivityManagerNative;
import android.app.StatusBarManager;
import android.app.IActivityManager;
import android.content.pm.IPackageDataObserver;
........
等等
不知应该引入哪个jar包

**Comment by luxiaoyu** [comment]
Cafe需要基于Android源码目录编译，你这样应该是基于SDK编译，不行的
如果只是使用Cafe的话，不需要编译Cafe本身，只要使用Cafe-3.1.zip中的apk和jar就行了

**Comment by rainy1216** [comment]
额。。。不只是使用，现在也要研究一下，我该怎样弄

**Comment by luxiaoyu** [comment]
看首页README

谢谢
鲁晓宇

发件人: rainy1216 [mailto:notifications@github.com]
发送时间: 2014年1月7日 11:53
收件人: BaiduQA/Cafe
抄送: Lu,Xiaoyu(Mobile Application RD)
主题: Re: [Cafe] com_baidu_cafe_remote项目下有错误 (#24)

额。。。不只是使用，现在也要研究一下，我该怎样弄
